[profile.default]
src = "src/contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
    "@chainlink/contracts/=node_modules/@chainlink/contracts/",
    "@openzeppelin/contracts@5.0.2/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts@4.8.3/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

